name: footings-dev
channels:
  - conda-forge
dependencies:
  # required
  - attrs
  - pandas
  - numpydoc=1.0.*
  - openpyxl

  # testing
  - pytest

  # development
  - flake8
  - black==19.*
  - pre-commit
  - sphinx
  - recommonmark
  - sphinx_rtd_theme
  - nbsphinx
  - ipython
  - ipykernel
