name: footings-dev
channels:
  - conda-forge
dependencies:
  # required
  - pip
  - attrs
  - numpy
  - pandas
  - numpydoc=1.0.*
  - openpyxl

  # testing
  - pytest
  - pytest-cov

  # development
  - flake8
  - black==19.*
  - pre-commit
  - sphinx
  - myst-nb
  - pydata-sphinx-theme
  - ipython
  - ipykernel
  - dask
  - pip:
    - nox
